hashgraph/hedera-sourcify

.github/ct.yaml
.github/workflows/chart-lint-test.yaml

This PR adds support for linting and testing the helm chart
Relates to #1 
This setup is mostly from [here](https://github.com/helm/charts-repo-actions-demo/blob/main/.github/workflows/lint-test.yaml)

Using helms chart-repo-actions demo to lint and test helm chart changes

---

src/server/controllers/verification/session-state/input-files.session-state.paths.yaml
src/server/controllers/verification/session-state/session-state.handlers.ts
src/server/controllers/verification/verification.common.ts
src/server/controllers/verification/verify/session/verify.session.handlers.ts
src/server/controllers/verification/verify/session/verify.session.paths.yaml

Add optional `dryrun` query parameter to the 2 endpoints of the session API (`/session/input-files` and `/session/verify-checked`) used by mirror-node explorer.
When the parameter is present and set to true, the result of the (successful) verification is not stored in the repository.
Fixes #90

feat: add dry run parameter to /session/input-files and /session/verify-checked end-points

---

hedera-patch/h5ai-nginx.patch

Update h5ai-nginx patch such that the Dockerfile checks out a specific commit in h5ai repository before applying the h5ai patch.
Fixes #83

chore: update h5ai-nginx patch to pin the h5ai revision

---

hedera-patch/h5ai-nginx.patch

Use checksummed address lookup in the repository `select-contract-form`. This allows the user to use the form with non-checksummed addresses.
Fixes #91 
**Checklist**

fix: repository lookup select contract form

---

.gitmodules

This PR ignores changes in the `h5ai-nginx` submodule **after** applying our customization patch `hedera-patch/h5ai-nginx.patch`. It does so by setting [`ignore = dirty`](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-dirty) in the submodule.
- Fixes #105 
**Checklist**

Ignore patched changes in submodule

---

src/server/controllers/verification/verify/session/verify.session.handlers.ts

Fix typo in query parameter expected by `/session/verify-checked endpoint`. The endpoint was expecting `dryRun` instead of `dryrun`. This does not reveal in the deployed code where the behaviour is case insensitive, but it reveals in the server testing environment.
Fixes #110 
This issue blocks PR for issue #93 which adds tests covering the use of this query parameter.

fix: typo in dryrun query parameter.

---

.github/workflows/tests.yaml
packages/contract-call-decoder/src/lib/ContractCallDecoder.spec.ts

Enable `contract-call-decoder` unit tests in CI by skipping failing IPFS test.
Fixes #
**Checklist**

ci: enable `contract-call-decoder` unit tests in CI by skipping IPFS test

---

test/helpers/assertions.js
test/server.js

Add tests for the `dryrun` query parameter recently added to the `/session/input-files` and `/session/verify-checked` API endpoints.
Fixes #93

chore: add server tests for dryrun query parameter

---

.github/workflows/flow-pr-title-check.yaml

This PR checks whether the PR title conforms with conventional commit message.
Fixes #113 
**Checklist**

chore: include PR title check workflow

---

charts/templates/server-repository/reset-job.yaml

This PR updates the reset jobs to use `cronjobs` instead of `jobs`.  It also changes to using `wget` from `curl`; prior to the wget change curl would simply pull the script to stdout but was not saved anywhere .  This change fixes that to get the file correct.
This change has been deployed into the test env

Update reset jobs making them recreatable

---

openapi.yaml

Remove session endpoints so that we can share the api-docs. Also fix the server drop-down which was showing always the local dev server.
I have included both prod and local server in the drop-down, but maybe the _Current REST API server_ suffices.
**Default server value**
**When the user opens the servers drop-down**
**Session endpoints label**
Fixes #
**Checklist**

fix: remove session endpoints and fix server drop-down

---

README.md
environments/.env.dev
environments/.env.docker.hedera
environments/.env.latest
environments/.env.stable
environments/docker-compose-hedera.yaml
environments/monitor.yaml
environments/repository.yaml
environments/s3.yaml
environments/server.yaml
scripts/hedera-reset-docker.sh

- add `REPOSITORY_PATH_HOST` .env variable (cherry pick commit from upstream ethereum/sourcify and use it in hedera specific files)
- align repository mount point inside the server container on what is used in (production) K8S deployment (i.e. `/data` instead of `/home/data/repository`)
- adjust network reset script accordingly to enable its use in production.
Fixes #125

chore: add Fix repository path

---

docs/tools.md

This PR adds a new `tools.md` doc where we can document how tools interact and work with the verification service. Currently, we added Foundry description.
Fixes #
**Checklist**

docs: add description how to verify contract with Foundry

---

.github/workflows/chart-lint-test.yaml

This PR modifies ... in order to support ...
* Updates the `chart-testing-action` version from `2.4.0` to `2.6.1`
Fixes #128 
Not sure how to test this outside of rebasing a failing PR with this branch (is there a better way though to test GH action changes?)

feat: Use version 2.6.1 where the cosign issue is expected to be fixed

---

README.md
environments/.env.dev
environments/.env.docker.hedera
environments/.env.latest
environments/.env.stable
environments/docker-compose-hedera.yaml
environments/monitor.yaml
environments/repository.yaml
environments/s3.yaml
environments/server.yaml
scripts/hedera-reset-docker.sh

(cherry picked from commit 2f2d5626e7e1d7f3a0f08eae8bd81b19395edb45)
This PR cherry-picks a change made in the main branch, which fixes the CONTRACT_PATH in reset script to match the configuration used in production. This is in case a new network reset would take place while the release 0.2 is still in production. 
The other changes in this commit concern the development/docker configurations and should not be relevant to the production environment.

chore: change CONTRACT_PATH in reset script

---

docs/tools.md

- add note about disabling etherscan
- add note about invoking programmatically (`hre.run`)
- Better DX when used as reference
- https://github.com/hashgraph/hedera-sourcify/issues/109
- https://github.com/NomicFoundation/hardhat/issues/4776#issuecomment-1915996510
Nil
**Checklist**
- https://github.com/hedera-dev/hedera-tokens/pull/1 and
- https://github.com/hedera-dev/hedera-tokens/pull/2

docs: update hardhat verification docs

---

charts/templates/server-repository/reset-job.yaml
charts/values.yaml

This PR modifies the reset job.  The reset job has to be run via mounting the PVC that is in use so that the correct filesystem locations are being reset.  There is a limitation in the CSI driver (aka `google-filestore-driver` in GCP Log explorer) where the driver has a subsystem puts locks on the volume mapped to the pod; this makes it impossible to get the volume to attach to a secondary pod on the same node where the server-repository lives .  This adding a secondary pod on the same node where the PVC is `bound` is documented as a working solution but the subsystem has a different setup.
Because of the limitation above, the reset job now runs `kubectl` to get the running server-repository pod, `exec`s into the pod and triggers the reset script.  There is a reset job …

Reset mount filesystem

---

README.md

Update README with a couple lines explaining how custom favicon files may be provided to the `ui` via `docker-compose` mount points. 
Fixes #54
Note the first part of issue #54 (setting default favicon to hedera branding) was long done.

chore: update README for customization of favicon.

---

README.md

Fixes #81.
Fixes #
**Checklist**

docs: improve `README` docs with project and service structure

---

ui/src/pages/Verifier/FileUpload.tsx

Fixes #61.
Fixes #
**Checklist**

docs: include allowed file extensions to upload in `ui`

---

packages/contract-call-decoder/src/lib/ContractCallDecoder.spec.ts

This PR fixes #162.
Fixes #
**Checklist**

fix: skip broken unit test for `contract-call-decoder`

---

charts/templates/server-repository/configmap.yaml
charts/templates/server-repository/deployment.yaml
charts/templates/ui/deployment.yaml
charts/values.yaml

This PR updates the sourcify chart with changes to support using upstream images. The changes are as follows:
- add servers.yaml, sourcify-chains.json, and local.js as Configmaps and mount them to the server container.
- Rework container image structure in both values.yaml and the corresponding deployments.
- Some minor linting of trailing spaces & newlines.

feat: Update chart to support upstream images

---

.github/workflows/push-images.yaml

Use `large` runner to fix CI image build.
Related to https://github.com/hashgraph/hedera-sourcify/pull/199.
Fixes #196.
**Checklist**

build: use `large` self-hosted runner to build and push images

---

.github/workflows/push-images.yaml

This PR setups `docker/build-push-action` cache in the workflow to improve building images in CI.
After the cache is filled, most of the `docker/build-push-action` step output should look like
```
#43 [linux/amd64 production 11/12] RUN npm ci --workspace=sourcify-server --include-workspace-root --omit=dev
#43 CACHED
```
**This reduces the workflow runtime from about an hour to a about minute when hitting the cache!**
> [!IMPORTANT]
> Each `docker/build-push-action` step needs to setup its [own scope](https://github.com/moby/buildkit/issues/2885) to avoid overwriting its cache between steps. The [docs](https://github.com/moby/buildkit?tab=readme-ov-file#github-actions-cache-experimental) regarding `scope` are not clear about this behavior.
Fixes #203. …

build: setup cache to build images in CI

---

charts/dashboards/Hedera-Sourcify-Logs.json
charts/dashboards/Hedera-Sourcify-Server.json
charts/dashboards/Hedera-Sourcify-Summary.json

This PR includes Grafana dashboards using Sourcify logs as input. Some of these dashboards were adapted from dashboards provided by the Sourcify team (see https://github.com/ethereum/sourcify/issues/1320#issuecomment-2178026829)
**Hedera Sourcify Summary**
**Hedera Sourcify Server**
**Hedera Sourcify Logs**
Fixes #144.
**Checklist**

docs: include Grafana dashboards using Sourcify logs

---

.github/CODEOWNERS

Limit the workflow folder to only platform-ci, platform-ci-committers, and release engineering managers group.
**Related Issue(s)**:
Fixes #278

chore: limit number of approvers on workflows folder

---

ui/package-lock.json
ui/package.json

This PR updates the `@babel/traverse` dependency to version 7.23.2 in the `./ui/` package
Fixes #312
- Added direct dependency on `@babel/traverse@^7.23.2` in `./ui/package.json`
- This forces resolution of nested dependencies to use the correct version
- Verified dependency resolution using `npm list @babel/traverse` in the UI package
- Built and tested the UI to ensure functionality is maintained

chore: update @babel/traverse in ui package
